buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Version 8.2.0 ko change karke 8.1.4 kar diya (Ultimate Cache Buster)
        classpath 'com.android.tools.build:gradle:8.1.4'
    }
}
tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
